apiVersion: apps/v1
kind: Deployment
metadata:
  name: p15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p15
  template:
    metadata:
      labels:
        app: p15
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p15
        ports:
        - containerPort: 80
